ensemble: 
  ne: 8 # TODO: 50
  transform: true
  num_models: 8 # TODO: 50
  state: [RATE_A1, RATE_A2, RATE_A3, RATE_A4, RATE_OP5, RATE_A5, RATE_A6, N_WT, N_H2]

  prior_RATE_A1:
    mean: '../init/rateA1.npz'
    var: 22500 # 5% of range
    limits: [0, 3000]

  prior_RATE_A2:
    mean: '../init/rateA2.npz'
    var: 40000 # 5% of range
    limits: [0, 4000]

  prior_RATE_A3:
    mean: '../init/rateA3.npz'
    var: 40000 # 5% of range
    limits: [0, 4000]

  prior_RATE_A4:
    mean: '../init/rateA4.npz'
    var: 40000 # 5% of range
    limits: [0, 4000]

  prior_RATE_OP5:
    mean: '../init/rateOP5.npz'
    var: 22500 # 5% of range
    limits: [0, 3000]
  
  prior_RATE_A5:
    mean: '../init/rateA5.npz'
    var: 160000 # 5% of range
    limits: [0, 8000]
  
  prior_RATE_A6:
    mean: '../init/rateA6.npz'
    var: 160000 # 5% of range
    limits: [0, 8000]

  prior_N_WT:
    mean: 12
    var: 9
    limits: [ 0, 40 ]

  prior_N_H2:
    mean: 144
    var: 144
    limits: [ 0, 400 ]

optim:
  maxiter: 1 # TODO: 10
  main_method: 'EnOpt' # TODO: 'LineSearch'  # LineSearch, EnOpt, SMCopt, TrustRegion
  method: 'GD'
  step_size_adapt: 0
  lsmethod: 1 # TODO: 0
  lsmaxiter: 2 # TODO: 5
  step_size: 0.2
  ftol: 0.001
  resample: 1 # TODO: 5
  epf:
    r: 1
    max_epf_iter: 1 # TODO: 5
    r_factor: 2
    tol_factor: 0.5
    conv_crit: 0.05
  savedata: ["epf"]
  save_folder: ""
  obj_scaling: [984000000.0, 2845473526.0]  # scaling for [CAPEX, NPV]

fwdsim:
  parallel: 8 # TODO: 35
  sim_limit: 24000
  runfile: DROGON
  windpower: '../init/wp_ens.npy'
  reporttype: dates
  datatype: [fopt, fgpt, fwpt, fwit, wthp a5, wthp a6]

  simoptions:
    #mpi: mpirun -np 5
    sim_flag: --parsing-strictness=low

  reportpoint: 
    start: '2020-07-01' 
    end: '2025-01-01' 
    freq: MS
  
  npv_const:
    wop: 471.7  # approx 75 USD/bbl
    wgp: 0.4    # USD/Sm3
    wwp: 37     # USD/Sm3
    wwi: 25     # USD/Sm3
    wem: 150    # USD/ton
    disc: 0.08  # 8% per year
    n_gt: 0     # number of gas turbines
    wt: 7200000.0   # USD/wind turbine capex (scaled by lifetime)
    h2: 180000.0   # USD/tonne H2 capex (scaled by lifetime)



  
  
  
  
